mkdir DisabledMods\.
move ace_advanced_ballistics.pbo DisabledMods\.
move ace_advanced_ballistics.pbo.ace_*.bisign  DisabledMods\.
move ace_advanced_fatigue.pbo  DisabledMods\.
move ace_advanced_fatigue.pbo.ace_*.bisign  DisabledMods\.
move ace_ai.pbo  DisabledMods\.
move ace_ai.pbo.ace_*.bisign  DisabledMods\.
move ace_aircraft.pbo  DisabledMods\.
move ace_aircraft.pbo.ace_*.bisign  DisabledMods\.
move ace_apl.pbo  DisabledMods\.
move ace_apl.pbo.ace_*.bisign  DisabledMods\.
move ace_arsenal.pbo  DisabledMods\.
move ace_arsenal.pbo.ace_*.bisign  DisabledMods\.
move ace_artillerytables.pbo  DisabledMods\.
move ace_artillerytables.pbo.ace_*.bisign  DisabledMods\.
move ace_atragmx.pbo  DisabledMods\.
move ace_atragmx.pbo.ace_*.bisign  DisabledMods\.
move ace_attach.pbo  DisabledMods\.
move ace_attach.pbo.ace_*.bisign  DisabledMods\.
move ace_backpacks.pbo  DisabledMods\.
move ace_backpacks.pbo.ace_*.bisign  DisabledMods\.
move ace_ballistics.pbo  DisabledMods\.
move ace_ballistics.pbo.ace_*.bisign  DisabledMods\.
move ace_captives.pbo  DisabledMods\.
move ace_captives.pbo.ace_*.bisign  DisabledMods\.
move ace_cargo.pbo  DisabledMods\.
move ace_cargo.pbo.ace_*.bisign  DisabledMods\.
move ace_chemlights.pbo  DisabledMods\.
move ace_chemlights.pbo.ace_*.bisign  DisabledMods\.
move ace_concertina_wire.pbo  DisabledMods\.
move ace_concertina_wire.pbo.ace_*.bisign  DisabledMods\.
#move ace_cookoff.pbo  DisabledMods\.
#move ace_cookoff.pbo.ace_*.bisign  DisabledMods\.
move ace_csw.pbo  DisabledMods\.
move ace_csw.pbo.ace_*.bisign  DisabledMods\.
move ace_dagr.pbo  DisabledMods\.
move ace_dagr.pbo.ace_*.bisign  DisabledMods\.
move ace_disarming.pbo  DisabledMods\.
move ace_disarming.pbo.ace_*.bisign  DisabledMods\.
move ace_disposable.pbo  DisabledMods\.
move ace_disposable.pbo.ace_*.bisign  DisabledMods\.
move ace_dogtags.pbo  DisabledMods\.
move ace_dogtags.pbo.ace_*.bisign  DisabledMods\.
move ace_dragging.pbo  DisabledMods\.
move ace_dragging.pbo.ace_*.bisign  DisabledMods\.
move ace_dragon.pbo  DisabledMods\.
move ace_dragon.pbo.ace_*.bisign  DisabledMods\.
move ace_explosives.pbo  DisabledMods\.
move ace_explosives.pbo.ace_*.bisign  DisabledMods\.
move ace_fastroping.pbo  DisabledMods\.
move ace_fastroping.pbo.ace_*.bisign  DisabledMods\.
move ace_fortify.pbo DisabledMods\.
move ace_fortify.pbo.ace_*.bisign  DisabledMods\.
move ace_field_rations.pbo  DisabledMods\.
move ace_field_rations.pbo.ace_*.bisign  DisabledMods\.
move ace_fire.pbo  DisabledMods\.
move ace_fire.pbo.ace_*.bisign  DisabledMods\.
move ace_fcs.pbo  DisabledMods\.
move ace_fcs.pbo.ace_*.bisign  DisabledMods\.
move ace_finger.pbo  DisabledMods\.
move ace_finger.pbo.ace_*.bisign  DisabledMods\.
move ace_flashlights.pbo  DisabledMods\.
move ace_flashlights.pbo.ace_*.bisign  DisabledMods\.
move ace_flashsuppressors.pbo  DisabledMods\.
move ace_flashsuppressors.pbo.ace_*.bisign  DisabledMods\.
move ace_fonts.pbo  DisabledMods\.
move ace_fonts.pbo.ace_*.bisign  DisabledMods\.
move ace_frag.pbo  DisabledMods\.
move ace_frag.pbo.ace_*.bisign  DisabledMods\.
move ace_gestures.pbo  DisabledMods\.
move ace_gestures.pbo.ace_*.bisign  DisabledMods\.
move ace_gforces.pbo  DisabledMods\.
move ace_gforces.pbo.ace_*.bisign  DisabledMods\.
move ace_goggles.pbo  DisabledMods\.
move ace_goggles.pbo.ace_*.bisign  DisabledMods\.
move ace_grenades.pbo  DisabledMods\.
move ace_grenades.pbo.ace_*.bisign  DisabledMods\.
move ace_gunbag.pbo  DisabledMods\.
move ace_gunbag.pbo.ace_*.bisign  DisabledMods\.
move ace_hearing.pbo  DisabledMods\.
move ace_hearing.pbo.ace_*.bisign  DisabledMods\.
move ace_hellfire.pbo  DisabledMods\.
move ace_hellfire.pbo.ace_*.bisign  DisabledMods\.
move ace_hitreactions.pbo  DisabledMods\.
move ace_hitreactions.pbo.ace_*.bisign  DisabledMods\.
move ace_hot.pbo  DisabledMods\.
move ace_hot.pbo.ace_*.bisign  DisabledMods\.
move ace_huntir.pbo  DisabledMods\.
move ace_huntir.pbo.ace_*.bisign  DisabledMods\.
move ace_interaction.pbo  DisabledMods\.
move ace_interaction.pbo.ace_*.bisign  DisabledMods\.
move ace_interact_menu.pbo  DisabledMods\.
move ace_interact_menu.pbo.ace_*.bisign  DisabledMods\.
move ace_inventory.pbo  DisabledMods\.
move ace_inventory.pbo.ace_*.bisign  DisabledMods\.
move ace_javelin.pbo  DisabledMods\.
move ace_javelin.pbo.ace_*.bisign  DisabledMods\.
move ace_kestrel4500.pbo  DisabledMods\.
move ace_kestrel4500.pbo.ace_*.bisign  DisabledMods\.
move ace_laser.pbo  DisabledMods\.
move ace_laser.pbo.ace_*.bisign  DisabledMods\.
move ace_laserpointer.pbo  DisabledMods\.
move ace_laserpointer.pbo.ace_*.bisign  DisabledMods\.
move ace_logistics_uavbattery.pbo  DisabledMods\.
move ace_logistics_uavbattery.pbo.ace_*.bisign  DisabledMods\.
move ace_logistics_wirecutter.pbo  DisabledMods\.
move ace_logistics_wirecutter.pbo.ace_*.bisign  DisabledMods\.
move ace_magazinerepack.pbo  DisabledMods\.
move ace_magazinerepack.pbo.ace_*.bisign  DisabledMods\.
move ace_map.pbo  DisabledMods\.
move ace_map.pbo.ace_*.bisign  DisabledMods\.
move ace_maptools.pbo  DisabledMods\.
move ace_maptools.pbo.ace_*.bisign  DisabledMods\.
move ace_map_gestures.pbo  DisabledMods\.
move ace_map_gestures.pbo.ace_*.bisign  DisabledMods\.
move ace_markers.pbo  DisabledMods\.
move ace_markers.pbo.ace_*.bisign  DisabledMods\.
move ace_maverick.pbo  DisabledMods\.
move ace_maverick.pbo.ace_*.bisign  DisabledMods\.
move ace_medical.pbo  DisabledMods\.
move ace_medical.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_ai.pbo  DisabledMods\.
move ace_medical_ai.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_blood.pbo  DisabledMods\.
move ace_medical_blood.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_damage.pbo  DisabledMods\.
move ace_medical_damage.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_engine.pbo  DisabledMods\.
move ace_medical_engine.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_feedback.pbo  DisabledMods\.
move ace_medical_feedback.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_gui.pbo  DisabledMods\.
move ace_medical_gui.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_statemachine.pbo  DisabledMods\.
move ace_medical_statemachine.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_status.pbo  DisabledMods\.
move ace_medical_status.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_treatment.pbo  DisabledMods\.
move ace_medical_treatment.pbo.ace_*.bisign  DisabledMods\.
move ace_medical_vitals.pbo  DisabledMods\.
move ace_medical_vitals.pbo.ace_*.bisign  DisabledMods\.
move ace_metis.pbo  DisabledMods\.
move ace_metis.pbo.ace_*.bisign  DisabledMods\.
move ace_microdagr.pbo  DisabledMods\.
move ace_microdagr.pbo.ace_*.bisign  DisabledMods\.
move ace_minedetector.pbo  DisabledMods\.
move ace_minedetector.pbo.ace_*.bisign  DisabledMods\.
move ace_missileguidance.pbo  DisabledMods\.
move ace_missileguidance.pbo.ace_*.bisign  DisabledMods\.
move ace_missionmodules.pbo  DisabledMods\.
move ace_missionmodules.pbo.ace_*.bisign  DisabledMods\.
move ace_mk6mortar.pbo  DisabledMods\.
move ace_mk6mortar.pbo.ace_*.bisign  DisabledMods\.
move ace_movement.pbo  DisabledMods\.
move ace_movement.pbo.ace_*.bisign  DisabledMods\.
move ace_mx2a.pbo  DisabledMods\.
move ace_mx2a.pbo.ace_*.bisign  DisabledMods\.
move ace_nametags.pbo  DisabledMods\.
move ace_nametags.pbo.ace_*.bisign  DisabledMods\.
move ace_nightvision.pbo  DisabledMods\.
move ace_nightvision.pbo.ace_*.bisign  DisabledMods\.
move ace_nlaw.pbo  DisabledMods\.
move ace_nlaw.pbo.ace_*.bisign  DisabledMods\.
move ace_noidle.pbo  DisabledMods\.
move ace_noidle.pbo.ace_*.bisign  DisabledMods\.
move ace_noradio.pbo  DisabledMods\.
move ace_noradio.pbo.ace_*.bisign  DisabledMods\.
move ace_norearm.pbo  DisabledMods\.
move ace_norearm.pbo.ace_*.bisign  DisabledMods\.
move ace_optics.pbo  DisabledMods\.
move ace_optics.pbo.ace_*.bisign  DisabledMods\.
move ace_optionsmenu.pbo  DisabledMods\.
move ace_optionsmenu.pbo.ace_*.bisign  DisabledMods\.
move ace_overheating.pbo  DisabledMods\.
move ace_overheating.pbo.ace_*.bisign  DisabledMods\.
move ace_overpressure.pbo  DisabledMods\.
move ace_overpressure.pbo.ace_*.bisign  DisabledMods\.
move ace_parachute.pbo  DisabledMods\.
move ace_parachute.pbo.ace_*.bisign  DisabledMods\.
move ace_pylons.pbo  DisabledMods\.
move ace_pylons.pbo.ace_*.bisign  DisabledMods\.
move ace_quickmount.pbo  DisabledMods\.
move ace_quickmount.pbo.ace_*.bisign  DisabledMods\.
move ace_rangecard.pbo  DisabledMods\.
move ace_rangecard.pbo.ace_*.bisign  DisabledMods\.
move ace_realisticnames.pbo  DisabledMods\.
move ace_realisticnames.pbo.ace_*.bisign  DisabledMods\.
move ace_realisticweights.pbo  DisabledMods\.
move ace_realisticweights.pbo.ace_*.bisign  DisabledMods\.
move ace_rearm.pbo  DisabledMods\.
move ace_rearm.pbo.ace_*.bisign  DisabledMods\.
move ace_recoil.pbo  DisabledMods\.
move ace_recoil.pbo.ace_*.bisign  DisabledMods\.
move ace_refuel.pbo  DisabledMods\.
move ace_refuel.pbo.ace_*.bisign  DisabledMods\.
move ace_reload.pbo  DisabledMods\.
move ace_reload.pbo.ace_*.bisign  DisabledMods\.
move ace_reloadlaunchers.pbo  DisabledMods\.
move ace_reloadlaunchers.pbo.ace_*.bisign  DisabledMods\.
move ace_repair.pbo  DisabledMods\.
move ace_repair.pbo.ace_*.bisign  DisabledMods\.
move ace_respawn.pbo  DisabledMods\.
move ace_respawn.pbo.ace_*.bisign  DisabledMods\.
move ace_safemode.pbo  DisabledMods\.
move ace_safemode.pbo.ace_*.bisign  DisabledMods\.
move ace_sandbag.pbo  DisabledMods\.
move ace_sandbag.pbo.ace_*.bisign  DisabledMods\.
move ace_scopes.pbo  DisabledMods\.
move ace_scopes.pbo.ace_*.bisign  DisabledMods\.
move ace_slideshow.pbo  DisabledMods\.
move ace_slideshow.pbo.ace_*.bisign  DisabledMods\.
move ace_smallarms.pbo  DisabledMods\.
move ace_smallarms.pbo.ace_*.bisign  DisabledMods\.
move ace_spectator.pbo  DisabledMods\.
move ace_spectator.pbo.ace_*.bisign  DisabledMods\.
move ace_spottingscope.pbo  DisabledMods\.
move ace_spottingscope.pbo.ace_*.bisign  DisabledMods\.
move ace_switchunits.pbo  DisabledMods\.
move ace_switchunits.pbo.ace_*.bisign  DisabledMods\.
move ace_tacticalladder.pbo  DisabledMods\.
move ace_tacticalladder.pbo.ace_*.bisign  DisabledMods\.
move ace_tagging.pbo  DisabledMods\.
move ace_tagging.pbo.ace_*.bisign  DisabledMods\.
move ace_thermals.pbo  DisabledMods\.
move ace_thermals.pbo.ace_*.bisign  DisabledMods\.
move ace_trenches.pbo  DisabledMods\.
move ace_trenches.pbo.ace_*.bisign  DisabledMods\.
move ace_tripod.pbo  DisabledMods\.
move ace_tripod.pbo.ace_*.bisign  DisabledMods\.
move ace_ui.pbo  DisabledMods\.
move ace_ui.pbo.ace_*.bisign  DisabledMods\.
move ace_vector.pbo  DisabledMods\.
move ace_vector.pbo.ace_*.bisign  DisabledMods\.
move ace_vehiclelock.pbo  DisabledMods\.
move ace_vehiclelock.pbo.ace_*.bisign  DisabledMods\.
move ace_vehicles.pbo  DisabledMods\.
move ace_vehicles.pbo.ace_*.bisign  DisabledMods\.
move ace_viewdistance.pbo  DisabledMods\.
move ace_viewdistance.pbo.ace_*.bisign  DisabledMods\.
move ace_weather.pbo  DisabledMods\.
move ace_weather.pbo.ace_*.bisign  DisabledMods\.
move ace_winddeflection.pbo  DisabledMods\.
move ace_winddeflection.pbo.ace_*.bisign  DisabledMods\.
move ace_yardage450.pbo  DisabledMods\.
move ace_yardage450.pbo.ace_*.bisign  DisabledMods\.
move ace_zeus.pbo  DisabledMods\.
move ace_zeus.pbo.ace_*.bisign  DisabledMods\.  

move ace_intelitems.pbo  DisabledMods\.
move ace_intelitems.pbo.ace_*.bisign  DisabledMods\.  
move ace_killtracker.pbo  DisabledMods\.
move ace_killtracker.pbo.ace_*.bisign  DisabledMods\.  
move ace_sitting.pbo  DisabledMods\.
move ace_sitting.pbo.ace_*.bisign  DisabledMods\.  
